export const mockData = [
	{
		Country: "South Africa",
		Date: "2020-11-14",
		Grapes: "shiraz/grenache",
		Image: "w0100",
		Name: "Secret Cellar",
		Other: undefined,
		Price: "8.99",
		Purchased: "Waitrose",
		Rating: "",
		Region: "Western Cape",
		Stock: "1",
		Style: "",
		Type: "Red",
		Variety: "Blend",
		Year: "2019"
	},
	{
		Country: "Italy",
		Date: "2020-10-27",
		Grapes: "syrah/nero d'avola",
		Image: "w0101",
		Name: "Nero Oro Riserva",
		Other: undefined,
		Price: "9.99",
		Purchased: "Majestic",
		Rating: "",
		Region: "Sicily",
		Stock: "1",
		Style: "bold and ripe",
		Type: "Red",
		Variety: "Blend",
		Year: "2017"
	},
	{
		Country: "Spain",
		Date: "2020-10-27",
		Grapes: "",
		Image: "w0102",
		Name: "The Guv'nor",
		Other: undefined,
		Price: "6.99",
		Purchased: "Majestic",
		Rating: "3",
		Region: "Valdepenas",
		Stock: "0",
		Style: "full",
		Type: "Red",
		Variety: "Tempranillo",
		Year: "2019"
	},
	{
		Country: "South Africa",
		Date: "2020-10-27",
		Grapes: "",
		Image: undefined,
		Name: "Gabb Family Vineyards",
		Other: undefined,
		Price: "10.99",
		Purchased: "Majestic",
		Rating: "",
		Region: "Coastal region",
		Stock: "2",
		Style: "",
		Type: "White",
		Variety: "Chardonnay",
		Year: "2019"
	},
	{
		Country: "Argentina",
		Date: "2020-10-27",
		Grapes: "",
		Image: undefined,
		Name: "BenMarco",
		Other: undefined,
		Price: "9.99",
		Purchased: "Majestic",
		Rating: "",
		Region: "Mendoza",
		Stock: "2",
		Style: "full",
		Type: "Red",
		Variety: "Malbec",
		Year: "2019"
	},
	{
		Country: "France",
		Date: "2020-10-27",
		Grapes: "grenache/syrah",
		Image: undefined,
		Name: "Cotes du Rhone E.Guigal",
		Other: undefined,
		Price: "11.99",
		Purchased: "Majestic",
		Rating: "",
		Region: "Cotes du Rhone",
		Stock: "1",
		Style: "smooth medium",
		Type: "Red",
		Variety: "Blend",
		Year: "2016"
	},
	{
		Country: "South Africa",
		Date: "2020-08-15",
		Grapes: "shiraz/mourvedre/viognier",
		Image: undefined,
		Name: "Kleine Zalze-Zalze",
		Other: undefined,
		Price: "5.99",
		Purchased: "Waitrose",
		Rating: "",
		Region: "Western Cape",
		Stock: "1",
		Style: "",
		Type: "Red",
		Variety: "Blend",
		Year: "2018"
	},
	{
		Country: "South Africa",
		Date: "2020-05-31",
		Grapes: "petit verdot/shiraz/cabernet franc/cabernet sauvignon",
		Image: undefined,
		Name: "Capaia-One",
		Other: undefined,
		Price: "11.99",
		Purchased: "Majestic",
		Rating: "4",
		Region: "Philadelphia",
		Stock: "2",
		Style: "full bodied",
		Type: "Red",
		Variety: "Blend",
		Year: "2016"
	},
	{
		Country: "South Africa",
		Date: "2020-10-04",
		Grapes: "",
		Image: undefined,
		Name: "Kanonkop-Kadette",
		Other: undefined,
		Price: "12.99",
		Purchased: "Majestic",
		Rating: "3.5",
		Region: "Stellenbosch",
		Stock: "2",
		Style: "",
		Type: "Red",
		Variety: "Pinotage",
		Year: "2018"
	},
	{
		Country: "Chile",
		Date: "2020-05-01",
		Grapes: "",
		Image: undefined,
		Name: "Cachapoal-Santa Carolina",
		Other: undefined,
		Price: "11.99",
		Purchased: "Ocado",
		Rating: "4",
		Region: "Valle de Cachapoal",
		Stock: "1",
		Style: "",
		Type: "Red",
		Variety: "Carmenere",
		Year: "2017"
	},
	{
		Country: "Spain",
		Date: "2018-10-31",
		Grapes: "tempranillo/graciano/mazuelo",
		Image: undefined,
		Name: "Campo Viejo-Reserva",
		Other: undefined,
		Price: "11",
		Purchased: "Tesco",
		Rating: "3.5",
		Region: "Rioja",
		Stock: "0",
		Style: "medium to full bodied",
		Type: "Red",
		Variety: "Blend",
		Year: "2013"
	},
	{
		Country: "Spain",
		Date: "2020-05-01",
		Grapes: "tempranillo/graciano/mazuelo",
		Image: undefined,
		Name: "Campo Viejo-Gran Reserva",
		Other: undefined,
		Price: "15",
		Purchased: "Ocado",
		Rating: "3.5",
		Region: "Rioja",
		Stock: "0",
		Style: "",
		Type: "Red",
		Variety: "Blend",
		Year: "2012"
	},
	{
		Country: "France",
		Date: "2018-11-06",
		Grapes: "merlot/cabernet sauvignon",
		Image: undefined,
		Name: "Chateau Cantin-Saint-Emilion Grand Cru",
		Other: undefined,
		Price: "25.99",
		Purchased: "Waitrose",
		Rating: "",
		Region: "Bordeaux",
		Stock: "1",
		Style: "medium to full bodied",
		Type: "Red",
		Variety: "Blend",
		Year: "2014"
	},
	{
		Country: "Argentina",
		Date: "2020-05-01",
		Grapes: "",
		Image: undefined,
		Name: "Trivento-Golden Reserve",
		Other: undefined,
		Price: "16",
		Purchased: "Ocado",
		Rating: "4",
		Region: "Lujan de Cuyo",
		Stock: "1",
		Style: "",
		Type: "Red",
		Variety: "Malbec",
		Year: "2017"
	},
	{
		Country: "South Africa",
		Date: "2018-11-06",
		Grapes: "",
		Image: undefined,
		Name: "Boschkloof-",
		Other: undefined,
		Price: "18.99",
		Purchased: "Waitrose",
		Rating: "",
		Region: "Stellenbosch",
		Stock: "0",
		Style: "medium to full bodied",
		Type: "Red",
		Variety: "Syrah",
		Year: "2015"
	},
	{
		Country: "England",
		Date: "2018-11-06",
		Grapes: "",
		Image: undefined,
		Name: "Denbies-Whitedowns",
		Other: undefined,
		Price: "18.99",
		Purchased: "Waitrose",
		Rating: "4",
		Region: "Surry",
		Stock: "0",
		Style: "Brut",
		Type: "Sparkling",
		Variety: "Chardonnay Dornfelder",
		Year: ""
	},
	{
		Country: "South Africa",
		Date: "2018-02-13",
		Grapes: "merlot/cabernet sauvignon",
		Image: undefined,
		Name: "Rupert & Rothschild-Classique",
		Other: undefined,
		Price: "18.95",
		Purchased: "Ocado",
		Rating: "3.5",
		Region: "Western Cape",
		Stock: "0",
		Style: "medium bodied",
		Type: "Red",
		Variety: "Blend",
		Year: "2014"
	},
	{
		Country: "Italy",
		Date: "2018-11-11",
		Grapes: "",
		Image: undefined,
		Name: "Sartirano Figli-Barbaresco Riserva",
		Other: "£36 Magnum bottle",
		Price: "18",
		Purchased: "Laithwaites",
		Rating: "",
		Region: "Barbaresco",
		Stock: "0",
		Style: "medium bodied",
		Type: "Red",
		Variety: "Nebbiolo",
		Year: "2005"
	},
	{
		Country: "Spain",
		Date: "2019-02-08",
		Grapes: "",
		Image: undefined,
		Name: "-Castillo de Javier Reserva",
		Other: undefined,
		Price: "14.99",
		Purchased: "",
		Rating: "3.5",
		Region: "Navarra",
		Stock: "0",
		Style: "medium to full bodied",
		Type: "Red",
		Variety: "",
		Year: "2006"
	},
	{
		Country: "France",
		Date: "2018-07-12",
		Grapes: "cabernet sauvignon/cabernet franc/merlot",
		Image: undefined,
		Name: "Chateau Haut Grand Champ-Yvon Mau",
		Other: undefined,
		Price: "13.99",
		Purchased: "Ocado",
		Rating: "3",
		Region: "Bordeaux",
		Stock: "0",
		Style: "",
		Type: "Red",
		Variety: "Blend",
		Year: "2014"
	},
	{
		Country: "South Africa",
		Date: "2019-02-03",
		Grapes: "",
		Image: undefined,
		Name: "Steenberg-",
		Other: "R249.00",
		Price: "13.84",
		Purchased: "34 South - Knysna Waterfront - South Africa",
		Rating: "3.5",
		Region: "Constantia",
		Stock: "0",
		Style: "full bodied",
		Type: "Red",
		Variety: "Merlot",
		Year: "2015"
	},
	{
		Country: "Australia",
		Date: "2020-05-26",
		Grapes: "",
		Image: undefined,
		Name: "Jip Jip Rocks-",
		Other: undefined,
		Price: "11.99",
		Purchased: "Ocado",
		Rating: "3.5",
		Region: "Padthaway",
		Stock: "0",
		Style: "",
		Type: "Red",
		Variety: "Shiraz",
		Year: "2018"
	}
];